import React from "react";
import { createContext, useContext, useState, useRef } from "react";
import { context } from "../App";
// pages
import Personal from "./InfoUpdateComponents/Personal";
import Experience from "./InfoUpdateComponents/Experience";
import RightSide from "./InfoUpdateComponents/RightSide";
import Knowledge from "./InfoUpdateComponents/Knowledge";
// pages

// styles
import CommonStyles from "./Styles/Common.module.css";
// styles

export const infoUpdateContext = createContext<any>("s");

export default function InfoUpdate() {
  const useAppContext1 = useContext(context);
  const {
    ExperienceDateStartRef,
    ExperienceDateEndRef,
    ExperienceTextAreaRef,
    aboutMeRef,
    cPage,
    cMoreKnowledge,
    sPage,
    cLanguage,
    sLanguage,
    cBGColor,
    sBGColor,
    cName,
    sName,
    cUsername,
    sUsername,
    cUploadImg,
    sUploadImg,
    cEmail,
    sEmail,
    cTel,
    sTel,
    cAboutMe,
    sAboutMe,
    cCorrect,
    sCorrect,
    cCorrect1,
    sCorrect1,
    cCorrect2,
    sCorrect2,
    cCorrect3,
    sCorrect3,
    cVisible,
    sVisible,
    cPosition,
    sPosition,
    cEmployer,
    sEmployer,
    cStartDate,
    sStartDate,
    cEndDate,
    sEndDate,
    cDescription,
    sDescription,
    cMoreExperience,
    sMoreExperience,
    cPosition1,
    sPosition1,
    cEmployer1,
    sEmployer1,
    cStartDate1,
    sStartDate1,
    cEndDate1,
    sEndDate1,
    cDescription1,
    sDescription1,
    cPosition2,
    sPosition2,
    cEmployer2,
    sEmployer2,
    cStartDate2,
    sStartDate2,
    cEndDate2,
    sEndDate2,
    cDescription2,
    sDescription2,
    cCorrect5,
    sCorrect5,
    cCorrect6,
    sCorrect6,
    cCorrect7,
    sCorrect7,
    cVisible1,
    sVisible1,
    cCourse,
    cQuality,
    cFinishDate,
    cDOE,
    cCourse1,
    sCourse1,
    cQuality1,
    sQuality1,
    cFinishDate1,
    sFinishDate1,
    cDOE1,
    sDOE1,
    cCourse2,
    sCourse2,
    cQuality2,
    sQuality2,
    cFinishDate2,
    sFinishDate2,
    cVisible2,
    sVisible2,
    cDOE2,
    sDOE2,
    courseRef,
    qualityRef,
    finishDateRef,
    DOERef,
  } = useAppContext1;

  return (
    <infoUpdateContext.Provider
      value={{
        courseRef,
        qualityRef,
        finishDateRef,
        DOERef,
        cPage,
        cMoreKnowledge,
        sPage,
        cLanguage,
        sLanguage,
        cBGColor,
        sBGColor,
        cName,
        sName,
        cUsername,
        sUsername,
        cUploadImg,
        sUploadImg,
        aboutMeRef,
        cVisible2,
        sVisible2,
        cEmail,
        sEmail,
        cTel,
        sTel,
        cAboutMe,
        sAboutMe,
        cCorrect,
        sCorrect,
        cCorrect1,
        sCorrect1,
        cCorrect2,
        sCorrect2,
        cCorrect3,
        sCorrect3,
        cVisible,
        sVisible,
        cPosition,
        sPosition,
        cEmployer,
        sEmployer,
        cStartDate,
        sStartDate,
        cEndDate,
        sEndDate,
        cDescription,
        sDescription,

        cMoreExperience,
        sMoreExperience,

        cPosition1,
        sPosition1,
        cEmployer1,
        sEmployer1,
        cStartDate1,
        sStartDate1,
        cEndDate1,
        sEndDate1,
        cDescription1,
        sDescription1,

        cPosition2,
        sPosition2,
        cEmployer2,
        sEmployer2,
        cStartDate2,
        sStartDate2,
        cEndDate2,
        sEndDate2,
        cDescription2,
        sDescription2,

        cCorrect5,
        sCorrect5,
        cCorrect6,
        sCorrect6,
        cCorrect7,
        sCorrect7,
        cVisible1,
        sVisible1,

        ExperienceDateStartRef,
        ExperienceDateEndRef,
        ExperienceTextAreaRef,
        cCourse,
        cQuality,
        cFinishDate,
        cDOE,
        cCourse1,
        sCourse1,
        cQuality1,
        sQuality1,
        cFinishDate1,
        sFinishDate1,
        cDOE1,
        sDOE1,
        cCourse2,
        sCourse2,
        cQuality2,
        sQuality2,
        cFinishDate2,
        sFinishDate2,
        cDOE2,
        sDOE2,
      }}
    >
      <div className={`${CommonStyles.container} ${CommonStyles.flexRow}`}>
        {cPage === 1 ? (
          <Personal />
        ) : cPage === 2 ? (
          <Experience />
        ) : cPage === 3 ? (
          <Knowledge />
        ) : (
          ""
        )}
        <RightSide />
      </div>
    </infoUpdateContext.Provider>
  );
}
